version: '3.8'

services:
  gfs1:
    build: .
    # image: ghcr.io/homelab-library/glusterfs
    privileged: true
    cap_add:
      - ALL
    networks:
      - gfsnet
    volumes:
      - "$HOME/glusterd/data1:/data"
      - "$HOME/glusterd/state1:/var/lib/glusterd"
      - "$PWD/rootfs/etc/ganesha:/etc/ganesha"
  gfs2:
    build: .
    # image: ghcr.io/homelab-library/glusterfs
    privileged: true
    cap_add:
      - ALL
    networks:
      - gfsnet
    volumes:
      - "$HOME/glusterd/data2:/data"
      - "$HOME/glusterd/state2:/var/lib/glusterd"
      - "$PWD/rootfs/etc/ganesha:/etc/ganesha"

volumes:
  gfsvol1: {}
  gfsvol2: {}

networks:
  gfsnet: